### ISSUE TITLE
IE 11: InvalidStateError

### ISSUE THREAD

**Issue by meredrica** [CrackerakiUA/ui-cropper#15]
Hi!
I've been trying to figure out this issue on IE11:
````
SCRIPT5022: InvalidStateError
ui-cropper.js (1,1)
````
The code I use is this:
````
<ui-cropper
  chargement="loading"
  area-init-size="{w: 400, h: 300}"
  max-canvas-dimensions="$ctrl.dimensions"
  area-type="rectangle"
  aspect-ratio="4/3"
  canvas-scalemode="full-width"
  image="$ctrl.cropImage"
  result-image="$ctrl.resultImage"
  result-image-size="'max'"
  result-blob="$ctrl.dataUrl"
>
</ui-cropper>
````
The error happens the moment the canvas is set to visible.
I could not figure out what's wrong, any ideas?

**Comment by meredrica** [comment]
Seems like this was closed in #9 but the compiled JS files don't reflect the change yet. Could you release this to NPM?

**Comment by CrackerakiUA** [comment]
sure, in few hours.

**Comment by CrackerakiUA** [comment]
Done

**Comment by DmitrySemchenok** [comment]
Seems like there is also an old version on bower. Could you please update it there too?

**Comment by MateuszAxence** [comment]
Are you sure to update npm? Because I still have that error? I also look into the source and I don't see that update.

**Comment by CrackerakiUA** [comment]
which version do you have?

**Comment by MateuszAxence** [comment]
I got the newest (1.0.4) using `npm install ui-cropper.`

**Comment by CrackerakiUA** [comment]
This is the latest.

**Comment by MateuszAxence** [comment]
Yup, but like I said that version not working for ie.
I changed provider in package.json on link from git: https://github.com/CrackerakiUA/ui-cropper.git
and seems to be ok and works.

**Comment by farorm** [comment]
+1, also getting InvalidStateError on IE11. Running version 1.0.4 installed with npm. Was there an workaround?

**Comment by hexadecy** [comment]
For release 1.0.4 on npmjs, files in compile folder are not up to date.

**Comment by hexadecy** [comment]
With 1.0.6 in Internet Explorer 11 on Windows 10: 
> SCRIPT5: Accès refusé.
> ui-cropper.js (1721,13)

**Comment by ynaveed** [comment]
There are some changes I made to fix this issue in IE. Works fine now. PR anyone?
