### ISSUE TITLE
CSS is broken and points to old cropper

### ISSUE THREAD

**Issue by karensg** [CrackerakiUA/ui-cropper#3]
CSS is broken and still point to the old directive (img-crop) to CSS is broken and still points to the old directive (img-crop)

**Comment by CrackerakiUA** [comment]
will fix in few hours.

**Comment by rickerd** [comment]
@karensg where is this broken and what?
Can point it out so i can help on this one.

**Comment by karensg** [comment]
The whole CSS points to the wrong directive. Just take a look in the CSS file

**Comment by CrackerakiUA** [comment]
I have pushed the fix, just need to build it, which i can do from my other pc. I will publish as soon as i can.

**Comment by rickerd** [comment]
Hi @karensg i've just compiled the new .js files so the new css would be available in the master branch

**Comment by karensg** [comment]
They are not available in the `compiled` folder yet. The library is still broken.

**Comment by rickerd** [comment]
@karensg i'm so sorry. It seemed that Gulp didn't overwrites the file if it already existed.
Now it does and a new version is made 1.0.3
https://github.com/CrackerakiUA/ui-cropper/releases/tag/1.0.3
